health:
  interval: 2
  timeout: 5

backends:
  - name: backend1
    addr: localhost:8080
  - name: backend2
    addr: localhost:8081
  - name: backend3
    addr: localhost:8082
  - name: backend4
    addr: localhost:8083

server:
  port: 8888
